### ISSUE TITLE
Docker Swarm

### ISSUE THREAD

**Issue by jpartain89** [htpcBeginner/docker-traefik#1]
So, my biggest want for dockerizing my environment is to use your incredibly detailed setup and be able to translate it into a swarm environment. (Think raspberry pi’s and what not). 

Swarm being a bit more complicated and figuring out how best to inter-link the different services securely seems to be my big wall I’m hitting in figuring this out. 

Is there any chance you guys could start including swarm stuff in these projects, not just for me but for anyone else out there that I’m sure are looking for the same thing.

**Comment by kevinelliott** [comment]
I'm looking for this as well.

**Comment by htpcBeginner** [comment]
I have a partially working swarm setup that I will share. However, i do not have time to work more on it at this point. May be after I complete the move to Traefik 2.
