### ISSUE TITLE
Glances IP not detected

### ISSUE THREAD

**Issue by Scales82** [htpcBeginner/docker-traefik#104]
Hey guys,
I cannot for the life of me get Glances to work right now. Traefik log is as follows:

`time="2020-11-21T05:49:38Z" level=error msg="service \"glances-svc\" error: unable to find the IP address for the container \"/glances\": the server is ignored" providerName=docker container=glances-docker-`

I've had this problem for a while, I think traefik 1 also did same thing. Any ideas? am i missing something stupid?

**Comment by dphildebrandt** [comment]
Hard to know unless you post your docker compose file. Just compare it line for line against the one in the repo.
