### ISSUE TITLE
Community support

### ISSUE THREAD

**Issue by shawnthompson** [htpcBeginner/docker-traefik#107]
Have you folks ever thought about having a community chat on something like Gitter or Discord so users can help each other in stead of opening issues with questions?

Maybe even IRC if you're old like me.

Great work here! Some of us noobs might need more help that other experts can simply answer. Like what is the `$SERVER_IP` variable, is it your host_IP or the docker IP?

Thanks again!

**Comment by htpcBeginner** [comment]
Enabled GitHub discussions for support.
