### ISSUE TITLE
Solution for mariadb MYSQL_ROOT_PASSWORD secrets file

### ISSUE THREAD

**Issue by alexander-t7** [htpcBeginner/docker-traefik#127]
Hi @htpcBeginner
First of all, thanks for your fantastic work on this repo!

I'm in the process of setting up my database container, and reading through the documentation at
https://docs.linuxserver.io/images/docker-mariadb#environment-variables-from-files-docker-secrets
I see, that the docker secret files need to have FILE__ at the beginning of the variable name rather than _FILE at the end (notice the double underscoure lines rather than a single one as usual). This seems strange to me, but I suppose there must be a reason why the guys over at linuxserver.io needed to solve it this way.

So instead of this:
- MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password # Not taking this pw during initialization
it should be:
- FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password

This worked for, allowing me to initialize the mariadb container without needing to define the root password after initialization through the command line.

**Comment by htpcBeginner** [comment]
Wonderful!. I will test this out and update.
