### ISSUE TITLE
Need Tutorial update for Traefik 2

### ISSUE THREAD

**Issue by GuyFromMars365** [htpcBeginner/docker-traefik#16]
I managed to sort of figure out Traefik 2.0+ from [docker-compose-t2.yml](https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml), but the official [Tutorial](https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/) that this repo references has still not been updated for Traefik 2.0+. Said tutorial mentions 

> **December 16, 2019:** We have published a first draft of the Docker Media Server setup with Traefik 2.1. Many of the apps work, but at this point, there are still things that need to be optimized/fixed. Please check our Docker-Traefik repo for relevant files. **A separate guide for Traefik 2 will be published in the coming days.**

3+ Months later and no updated tutorial. :( Will a revised one come out soon?

**Comment by adradloff** [comment]
if you look at my repository I have a working Traefik 2 config with plex, radarr, sonarr, qbittorrent, piwigo, pihole, and a few others.  Not sure if it will help you or not.  https://github.com/adradloff/docker-HTPC  Its my first git so I'm still learning a bit, the readme may not be so clear as of yet.

**Comment by htpcBeginner** [comment]
I am working on it guys. I promise!

**Comment by Joeharrison94** [comment]
@htpcBeginner @adradloff Hi guys are you having issues getting traefik.domain.com working in your setup I am trying to allow access to the traefik ui using the google oauth but it just gives me a server not found error in my browser, I have altered the - "traefik.http.routers.traefik-rtr.middlewares label in the traefik container to include the oauth@file am I missing something must have tried every combination I can think of (apologies for the noob question I am still getting my head around v2) could it be to do with adding the oauth file in the above and then adding another label for the middleware to use chain-oauth@file as as it stands it doesnt work at all when I add the oauth

**Comment by adradloff** [comment]
@Joeharrison94 In my docker-compose file I have this line - "traefik.http.routers.traefik-rtr.middlewares=traefik-headers,middlewares-rate-limit@file,chain-oauth@file"  The last part(,chain-oauth@file"  is what I added to get Google oauth to work.  once logged in it works just fine and takes me to the traefik dashboard.

**Comment by Joeharrison94** [comment]
That’s odd it doesn’t work for me, are you using the same yml file as in your repo

**Comment by adradloff** [comment]
Yes I am. I updated it yesterday and rebuilt it on my server, it all is running as it should.

**Comment by Joeharrison94** [comment]
ok so I have identical config to you yet when I launch my compose all apps work except for traefik, it worked once then never again, I also noticed that when I run docker compose up it shows the name of the traefik container is docker_traefik_1 which is very odd, and when I go to traefik.mydomain.co.uk it redirects to trafik.mydomain.co.uk (in a browser that has already passed oauth) but in incognito mode it goes to oauth so im sure that works but it seems something is wrong with my traefik container but I dont know how to remove it and start fresh with just that one container.

**Comment by Joeharrison94** [comment]
Fixed the container name but the rest is still the same

**Comment by Joeharrison94** [comment]
Could you tell me the process on how to refresh the certs and remove traefik and readd it as it isn’t working as I mentioned before

**Comment by adradloff** [comment]
docker stop traefik - stops the container
docker rm traefik - removes the container
rm traefik2/acme/acme.json - removes -traefik certificates
touch traefik2/acme/acme.json - recreates a blank file
chmod 600 traefik2/acme/acme.json - give it correct permissions to traefik

If you want to test just traefik create a new yml file with only the traefik and oauth. make sure you have the network section too.

ensure you uncomment out - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" to ensure it recreates your certificates in the acme.json file.  after first run re comment it out and re run your yml file to ensure wildcard certs.

**Comment by Joeharrison94** [comment]
Ok no problem I’ll give it a whirl tomorrow thank you, do you think it is an issue that sabnzbd traefik port is 8080 also ? And what could cause the weird browser redirection to trafik instead of traefik

**Comment by adradloff** [comment]
the weird redirection would most likely be a misspelling in the config.  
As for the port I would try a different port and see if that works.

**Comment by Joeharrison94** [comment]
ok so i did all of the above deleted the container, and acme json uncommented the line and changed the port yet im still getting a redirect to trafik, there is no reference of this in any config, I think it is caching it somewhere how can I fix this :/

**Comment by Joeharrison94** [comment]
also if i go to the local ip and 9090 im getting a 404 error

**Comment by Joeharrison94** [comment]
thats the port i chose instead of 8080

**Comment by htpcBeginner** [comment]
@Joeharrison94 when you access locally (local IP) are you using HTTP or https? 

I would strong suggest you to not have any other apps running. First get your traefik 2 and dashboard up and running. Check acme.json to make sure certs have been pulled. 

Then start adding other apps.

**Comment by Joeharrison94** [comment]
I’ve cracked it! Something was wrong in the image files I deleted the image and pulled it again and used my old config with the uncommented the line and hey presto :D hopefully it carries on working when I down it to comment out the line

**Comment by htpcBeginner** [comment]
That can certainly happen. I was thinking about it and would have been my next suggestion. I am closing this issue.

**Comment by yashodhank** [comment]
**middlewares.toml** contents & https://github.com/htpcBeginner/docker-traefik/blob/master/traefik2/rules/middlewares-chains.toml.example (my middlewares-chains.toml is same used for example)
```
  [http.middlewares.middlewares-basic-auth]
    [http.middlewares.middlewares-basic-auth.basicAuth]
#      users = [
#        "user:$apsdfswWvC/6.$E3FtsfTntPC0wVJ7IUVtX1",
#      ]
      realm = "Traefik2 Basic Auth"
      usersFile = "/shared/.htpasswd" #be sure to mount the volume through docker-compose.yml

[http.middlewares]
  [http.middlewares.middlewares-rate-limit]
    [http.middlewares.middlewares-rate-limit.rateLimit]
      average = 100
      burst = 50

# Available Header Options: 
#####https://github.com/unrolled/secure#available-options
#####https://docs.traefik.io/middlewares/headers/
# A great resource for these headers is your preferred browser's docs. Firefox: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
# https://developers.google.com/search/reference/robots_meta_tag
# https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Clickjacking_Defense_Cheat_Sheet.md
# CSP for VNC: https://github.com/cockpit-project/cockpit/pull/5932
# Check headers here, don't include OAuth when checking headers, otherwise you are checking google's headers: https://securityheaders.com
# or check them here: https://observatory.mozilla.org/

# CAUTION: Any headers defined in docker-compose (yml) will OVERWRITE ALL of the headers defined below.

  [http.middlewares.middlewares-secure-headers]
    [http.middlewares.middlewares-secure-headers.headers]
      accessControlAllowMethods= ["GET", "OPTIONS", "PUT"]
      accessControlMaxAge = 100
      hostsProxyHeaders = ["X-Forwarded-Host"]
      sslRedirect = true
      stsSeconds = 63072000
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true
#      frameDeny = true #overwritten by customFrameOptionsValue
      customFrameOptionsValue = "allow-from https:example.com" #CSP takes care of this but may be needed for organizr. 
      contentTypeNosniff = true 
      browserXssFilter = true 
#      sslForceHost = true # add sslHost and all of the 
#      sslHost = "example.com"
      referrerPolicy = "same-origin" 
#      Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
#      the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
#      contentSecurityPolicy = "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
      featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';" 
      [http.middlewares.middlewares-secure-headers.headers.customResponseHeaders]
        X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex,"
        server = ""

  [http.middlewares.middlewares-oauth]
    [http.middlewares.middlewares-oauth.forwardAuth]
      address = "http://oauth:4181" # Make sure you have the OAuth service in docker-compose.yml
      trustForwardHeader = true
      authResponseHeaders = ["X-Forwarded-User"]
```
```
docker logs -tf --tail="50" traefik
2020-04-22T22:03:28.742221087Z time="2020-04-22T22:03:28Z" level=info msg="Configuration loaded from flags."
2020-04-22T22:03:29.748432038Z time="2020-04-22T22:03:29Z" level=error msg="middleware \"chain-oauth@file\" does not exist" entryPointName=https routerName=oauth-rtr@docker
2020-04-22T22:03:29.748475208Z time="2020-04-22T22:03:29Z" level=error msg="middleware \"chain-oauth@file\" does not exist" routerName=traefik-rtr@docker entryPointName=https
```
