### ISSUE TITLE
portainer "exec console" not working

### ISSUE THREAD

**Issue by Bockiii** [htpcBeginner/docker-traefik#160]
Greetings,

I love this thing! it's the most comprehensive guide on setting all of the containers up behind traefik, so massive kudos to you.

I assume "everyone" should have this issue since I basically just used your -t2.yml config.

When I use portainer through its public url (portainer.example.com), portainer itself works just fine. The only thing that doesnt work is the "exec console" that lets you attach to the terminal window of that container. When I hit "connect", it does not open the black window (there is a short loading of something but its immediately gone again).

When I'm using a second portainer container with the local IP, the console windows works just fine.

I am using google oauth in front of the url and have tried both local authentication and google oauth user authentication, same behavior on both.

Is your portainer behaving the same way?

I am running the latest versions on all the containers.
Traefik: livarot
Portainer: 2.1.1

**Comment by brandonhowlett** [comment]
Agreed, an invaluable resource!

I'm also on 2.1.1 and experiencing the same thing with the console, however, I've associated portainer with a path.

```  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer.docker
    networks:
      - traefik-web
      - traefik-common
    cpuset: 0,4
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=America/Phoenix
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=HostHeader(`sub.domain.com`) && PathPrefix(`/portainer`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      - traefik.http.routers.portainer.middlewares=chain-add-slash@file, chain-oauth@file
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      
      - traefik.http.routers.portainer-edge.entrypoints=websecure
      - traefik.http.routers.portainer-edge.rule=HostHeader(`sub.domain.com`) && PathPrefix(`/portainer-edge`)
      - traefik.http.routers.portainer-edge.tls=true
      - traefik.http.routers.portainer-edge.tls.certresolver=cloudflare
      - traefik.http.routers.portainer-edge.middlewares=chain-add-slash@file, chain-oauth@file
      - traefik.http.routers.portainer-edge.service=portainer-edge
      - traefik.http.services.portainer-edge.loadbalancer.server.port=8000
    volumes:
      - /mnt/user/appdata/portainer-ce:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - 8000:8000
#      - 9000:9000
```

Curious of any insights.

**Comment by raulvasquez** [comment]
Curious about this as well. Consoles are not working for me with google oauth in portainer.

**Comment by Bockiii** [comment]
Oh man, i found it :D

the socket proxy was the culprit :D It has a setting called "exec" which is disabled by default. Set that to 1 and it works :D

So @raulvasquez and @brandonhowlett : Change the setting and it will work :D

**Comment by l4rm4nd** [comment]
> Oh man, i found it :D
> 
> the socket proxy was the culprit :D It has a setting called "exec" which is disabled by default. Set that to 1 and it works :D
> 
> So @raulvasquez and @brandonhowlett : Change the setting and it will work :D

Hi @Bockiii , could you elaborate further? I don't really understand where I have to enable the "exec" setting.

**Comment by Bockiii** [comment]
Sure. This line https://github.com/htpcBeginner/docker-traefik/blob/3731045c70f1fa305324c0deb8b292001a9461f5/docker-compose-t2.yml#L286

Change it to 1 and it works.
