### ISSUE TITLE
Wordpress traefik rule chain-authelia-wp@file

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#165]
Hi the rule you are using chain-authelia-wp@file is not listed in your chains example, please can you share this.

Thank you

**Comment by htpcBeginner** [comment]
https://github.com/htpcBeginner/docker-traefik/commit/4f8884baa6abb9865d8d329456eb7df2fd71ff39#diff-1e9b5b49c61bf6d0605a8955a0d4be200980cb361caed18041f92ce793be6890
