### ISSUE TITLE
Synology DSM 7 - free port 80/443

### ISSUE THREAD

**Issue by Daniel-WW** [htpcBeginner/docker-traefik#178]
After upgrading my Synology NAS 918+ on DSM 7, I'm no longer able to "free" prot 80 and 443. 
Under DSM 6.2 I could change the port 80 and 443 by using a boot script (change-ports.sh), like described [here](https://www.smarthomebeginner.com/synology-docker-media-server/). 

Now in DSM 7 obviously the script doesn't work and Nginx (from DSM) is always blocking the port.

**Comment by htpcBeginner** [comment]
https://github.com/htpcBeginner/docker-traefik/blob/master/scripts/synology/switch_ports.sh.example

**Comment by scrapix** [comment]
thank you tons for "switching_ports.sh" @htpcBeginner
