### ISSUE TITLE
traefik - which version?

### ISSUE THREAD

**Issue by SpeedmaxX** [htpcBeginner/docker-traefik#179]
Hi, thank you for your awesome [guide](https://www.smarthomebeginner.com/traefik-2-docker-tutorial/) 
I saw, that version 2.5 was just released. Are you still using livarot (is that 2.4?) and does the guide also fit on that version?
Best regards,
Markus

**Comment by modem7** [comment]
It does not work directly with 2.5.

There's a few deprecated options such as sslredirect and FeaturePolicy.

**Comment by grasuoare** [comment]
up

**Comment by htpcBeginner** [comment]
Changes are needed in middleware for 2.5. I just upgraded to 2.5. I have not pushed the changes to the repo.

**Comment by grasuoare** [comment]
ok. @htpcBeginner . we will wait for the push. Thanks you !

**Comment by grasuoare** [comment]
@htpcBeginner could you share here the changes, please? :)

**Comment by htpcBeginner** [comment]
Pushed changes to the repo for traefik v2.5.
