### ISSUE TITLE
Warning - secrest variables not set

### ISSUE THREAD

**Issue by gcraenen** [htpcBeginner/docker-traefik#182]
sudo docker-compose -f docker-compose-t2.yml up
WARNING: The CLOUDFLARE_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The GOOGLE_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The GOOGLE_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The OAUTH_SECRET variable is not set. Defaulting to a blank string.
WARNING: The MY_EMAIL variable is not set. Defaulting to a blank string.
Starting socket-proxy ... done
Starting oauth        ... done
Starting traefik      ... done

Put all these variables as secret files in the secrets directory as per the https://www.smarthomebeginner.com/traefik-docker-security-best-practices/#8_Use_Docker_Secrets site. Is does not seem to work.

**Comment by htpcBeginner** [comment]
https://github.com/htpcBeginner/docker-traefik/commit/a2adaaeb5a0653c11c44b5b7690a9b3053494113
