### ISSUE TITLE
Only pihole and hassio certs being created (t2)

### ISSUE THREAD

**Issue by robflate** [htpcBeginner/docker-traefik#19]
I'm running the t2 version and the services are reachable and working through oauth but the certs aren't being created (except for pihole and hassio). I'm not getting any errors in the traefik log so I don't think they're even being requested. Is there any further info I can provide that might help me resolve this? Thanks.

**Comment by htpcBeginner** [comment]
Try adding this label to each of the services in the compose file and see if that helps:

`      - "traefik.http.routers.service-rtr.tls.certresolver=dns-cloudflare"`

make sure 'service-rtr' is customized to your situation.

**Comment by robflate** [comment]
Great! That works. Downside is it generates a separate challenge TXT record in Cloudflare and a separate certificate in acme.json for each service rather than use a wildcard. I assume it's something to do with this #15. FYI, my domain is with Google and DNS through Cloudflare.

**Comment by htpcBeginner** [comment]
Hmm....

I removed that line based on #15 and all my services appear to serve the correct certificate. 

But, I did start traefik2 first and let it pull the certs before adding more services. I do not know if this had anything to do with that.

**Comment by robflate** [comment]
So, your `acme.json` just has a wildcard cert but not certs for each service?

Also, what manual DNS entries do you have in Cloudflare related to this setup? Do you just have;

`A   |   example.com   |   Public IP   |   Auto   |   DNS only`

or do you also have a manual wildcard like;

`CNAME   |   *   |   example.com   |   Auto   | DNS only`

or is that generated automatically?

Finally, did you run traefik on its own without `- "traefik.http.routers.service-rtr.tls.certresolver=dns-cloudflare"` or with? And did you do it with line 102 of docker-compose-t2.yml uncommented and then comment it out after?

Thanks

**Comment by htpcBeginner** [comment]
My DNS entries are explained here:
https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/#Dynamic_DNS_or_Your_Own_Domain_Name

An A record for the domain pointing to my IP.
A CNAME record for * pointing to @ (root domain).
These two must be manually added.

No, I only have certs for example.com and *.example.com in my acme.json. That is it.

I started with traefik with certresolver enabled. Once the dashboard was up and the certs were pulled I commented out the line. 

I had a max of 2 auto entered DNS challenge entries in my DNS records.

**Comment by robflate** [comment]
That's how I have mine setup.

I just added a few more services (Plex, Radarr and Sonarr) and for reasons unknown to me, the main cert and wildcard cert appeared in acme.json. Unfortnately I can't say exactly what made it start working though. Anyway, it's working now. Thanks for your help.

**Comment by Joeharrison94** [comment]
@robflate do you have pi hole working with traefik 2 if so would you mind sharing how you have it set up I can’t for the life of me get it working with traefik 2

**Comment by htpcBeginner** [comment]
I have updated my repo files. With the latest updates, you can add this traefik 2 label:

      - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file"

**Comment by Joeharrison94** [comment]
@htpcBeginner would you be able to let me know how you managed to get dns sec working in your pi hole container I have pi hole working but when I connect to my container and pull the cloudflared amd64 image and extract it all, when it comes to creating the conf file and script I can’t as the pi hole container has no tools to do so ? Thanks I’m using traefik 2 but without it addressing for reference
