### ISSUE TITLE
Connecting qBittorrent to Radarr/Sonarr

### ISSUE THREAD

**Issue by vmcosco** [htpcBeginner/docker-traefik#196]
I am in the process of moving all of my services over to Docker based on your guide (which is great).  So far I have Traefik, OAuth, Portainer, Flame and qBittorrent.   My host IP (Ubuntu Server) is 192.168.10.26.  My Traefik network is 192.168.90.0 and qBit is on 192.168.90.131:8080 and accessible via qbit.mydomain.com.  Sonarr and Radarr are still sitting in a Windows VM on 192.168.10.24.  Is it possible for me to connect qBit with those services as they sit now?  In the qBit client settings in Radarr I tried multiple combinations and I cannot get a connection.

I plan to move Sonarr and Radarr over but it will take a bit effort so I am not ready quite yet.

**Comment by htpcBeginner** [comment]
Yes. If you expose port 8080 from 192.168.90.131:8080 to the host port 8080 (192.168.10.26:8080). Then you should be able to access it from your windows VM. Reopen if you have issues.
