### ISSUE TITLE
With your configuration, Traefik Dashboard will never stop loading

### ISSUE THREAD

**Issue by stevie86** [htpcBeginner/docker-traefik#198]
Hi!
I used your extensive tutorial to setup a basic traefik portainer docker stack - however, I keep failing at the very basic setup of the traefik dashboard.
It will create the container(s), query the certificate correctly, but then the dashboard will not be available... it will keep loading forever, the log showing a TLS handshake error. See attached the log:
[traefik-logs.log](https://github.com/htpcBeginner/docker-traefik/files/7706457/traefik-logs.log)

If I then add the part for the portainer container, I only get a 404 error.
What's wrong? I have the required .htaccess and middlewares file in place.
[docker-compose-t2-yml.txt](https://github.com/htpcBeginner/docker-traefik/files/7706492/docker-compose-t2-yml.txt)
[middlewares-toml.txt](https://github.com/htpcBeginner/docker-traefik/files/7706498/middlewares-toml.txt)
Any help will be greatly appreciated!
Thanks!
Best regards!

**Comment by XargsUK** [comment]
Having the same issue. Will update if I find out the cause

**Comment by Maynardnaze** [comment]
get it a basic traefik dashboard working, then add wildcard certs etc
im stuck on middleware-redirect-schemes missing from middlewares.yml/toml

**Comment by boywiz** [comment]
> get it a basic traefik dashboard working, then add wildcard certs etc im stuck on middleware-redirect-schemes missing from middlewares.yml/toml

@Maynardnaze your answer is in this other open issue: https://github.com/htpcBeginner/docker-traefik/issues/187

**Comment by htpcBeginner** [comment]
> get it a basic traefik dashboard working, then add wildcard certs etc im stuck on middleware-redirect-schemes missing from middlewares.yml/toml

This has been fixed.

**Comment by htpcBeginner** [comment]
From the log

> Serving default certificate for request: \"\""

That does not seem right. No domain name is specified or did you redact it?
