### ISSUE TITLE
MQTT?

### ISSUE THREAD

**Issue by sterlinm** [htpcBeginner/docker-traefik#2]
Could you provide some more details on how you set up the config and password files for MQTT?

**Comment by htpcBeginner** [comment]
As in the compose file, mosquitto username and passwords are stored in the passwd file:
`${USERDIR}/docker/mosquitto/config/passwd:/mosquitto/config/passwd`

this file has username and password in the following format:

`USER:PASSWORD`

passwords must be created using the mosquitto_passwd command: https://mosquitto.org/man/mosquitto_passwd-1.html
