### ISSUE TITLE
Stuck with " acme: Waiting for DNS record propagation"

### ISSUE THREAD

**Issue by theluke** [htpcBeginner/docker-traefik#207]
Hello there!
I am following [the guide](https://www.smarthomebeginner.com/traefik-2-docker-tutorial/), the best I can, despite my limited understanding.

I have created my own domain on Cloudflare, it uses the free plan.

I followed [these steps}(https://www.smarthomebeginner.com/cloudflare-settings-for-traefik-docker/) too to configure things properly.

However, when I start the **Traefik2** container, the message `acme: Waiting for DNS record propagation` goes on until it times out.

I am lost since I do not know what to change.

The (redacted) output from `acme.json` does not seem correct either:

> {
  "dns-cloudflare": {
    "Account": {
      "Email": "fake@email.com",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:fake@email.com"
          ]
        },
        "uri": "https://acme-staging-v02.api.letsencrypt.org/acme/acct/39438708"
      },
      "PrivateKey": "a lot of stuff",
      "KeyType": "4096"
    },
    "Certificates": null
  }
}l

**Comment by theluke** [comment]
We can close the issue. I just had to wait longer. I need to find a way to increase the timeout

**Comment by PrplHaz4** [comment]
> We can close the issue. I just had to wait longer. I need to find a way to increase the timeout

try setting `CLOUDFLARE_PROPAGATION_TIMEOUT`
https://go-acme.github.io/lego/dns/cloudflare/#additional-configuration

**Comment by theluke** [comment]
thank you @PrplHaz4 , I will give it a shot
