### ISSUE TITLE
Docker swarm persistent storage with SQLite based containers? 

### ISSUE THREAD

**Issue by n1nj4888** [htpcBeginner/docker-traefik#21]
Hi!

What are you using for shared persistent storage between docker swarm nodes for the `docker-compose-t1-swarm.yml` services?

The reason I ask is that you specify a $USERHOME directory but do not specify a specific node constraint for sonarr/radarr/tautulli services so I assume $USERHOME is a network share and the containers can run on any node with access to shared storage? If so, do you not get constantly corrupted sonarr/radarr/tautulli databases given they use sqlite which does not work well at all with network shares (see [Sonarr Issue #1886)](https://github.com/Sonarr/Sonarr/issues/1886)

**Comment by gzecchi** [comment]
Hi @n1nj4888,

the most common solution for persistent storage with Docker Swarm is GlusterFS.

You should create a Gluster Volume, mount it on all nodes belonging to swarm and you'll see the same data present in $USERHOME replicated on all nodes at low level, without any network share.

GZ

**Comment by JohnShortland** [comment]
> Hi @n1nj4888,
> 
> the most common solution for persistent storage with Docker Swarm is GlusterFS.
> 
> You should create a Gluster Volume, mount it on all nodes belonging to swarm and you'll see the same data present in $USERHOME replicated on all nodes at low level, without any network share.
> 
> GZ

This still causes data corruption for SQLite containers, I test this method previously and ended up with a corrupted Radarr, Sonarr, Lidarr and Plex etc

**Comment by gzecchi** [comment]
Hi @JohnShortland,

have you tried with GlusterFS 7.x?

**Comment by JohnShortland** [comment]
> Hi @JohnShortland,
> 
> have you tried with GlusterFS 7.x?

I tried around Feb 2020 so yes would have been GlusterFS 7 as that was released in Nov 2019

**Comment by n1nj4888** [comment]
@JohnShortland - I’ve been running GlusterFS 7.x and lately 8.x for a while now and haven’t seen any SQLite corruption. When you say you tried in Feb 2020, did you add the gluster repositories and install from there or did you just use the standard Linux/Ubuntu repository? If you used the standard repository, last I checked these were very out of date.

**Comment by JohnShortland** [comment]
@n1nj4888 Just checked the issue on the sonarr github and its March 2020 that I tried GlusterFS 7 and experienced corruption.

**Comment by n1nj4888** [comment]
Working fine for me on GlusterFS 7/8. Assume you used the glusterFS client to mount the glusterFS volume and not NFS?
