### ISSUE TITLE
Error renewing certificate from LE

### ISSUE THREAD

**Issue by marapavelka** [htpcBeginner/docker-traefik#210]
I sometimes see this error in the Traefik log:
```time="2022-01-05T13:01:01Z" level=error msg="Error renewing certificate from LE: {mydomain.eu [*.mydomain.eu]}, error: one or more domains had a problem:\n[*.mydomain.eu] time limit exceeded: last error: NS wanda.ns.cloudflare.com. returned REFUSED for _acme-challenge.mydomain.eu.\n[mydomain.eu] time limit exceeded: last error: NS mark.ns.cloudflare.com. returned REFUSED for _acme-challenge.mydomain.eu.\n" providerName=dns-cloudflare.acme```
How can I fix it? Increase the time limit somewhere?

**Comment by PSJMcNeill** [comment]
Any success with this? My certificate has expired and Traefik just says it is timing out 


acme: cleaning up failed: cloudflare: could not find the start of authority for _acme-challenge.mydomain.net.: read udp 172.18.0.11:38663->1.0.0.1:53: i/o timeout "

**Comment by marapavelka** [comment]
Unfortunately no, the certificate still cannot be renewed. Even if I delete the acme.json file, create a new empty one (with chmod 600), it doesn't create a new certificate. Everything works and the site reports that the connection is secure. But when I look at the certificate details in the browser, I find that the issuer is not LetsEncrypt but Cloudflare. I may have made a mistake right at the start somewhere when setting up Treafik and Cloudflare, but I have no idea how to fix it :(

**Comment by tskulbru** [comment]
I had the exact same issue and I believe its due to the secrets not working as they should. This remedy this, I changed the following environment variables from the old `/run/....:` to this instead.

```
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
```

Dont forget to add your variables to your .env file, or directly inline them. I also had to empty the acme.json to make traefik properly refresh everything. Im not sure exactly why it didnt work with secrets though.

**Comment by htpcBeginner** [comment]
Make sure you have cf_email and cf_api_key in the secrets folder. These were renamed from cloudflare_email and cloudflare_api_key recently. If not, using environmental variables like @tskulbru mentioned is another way but i recommend secrets.

**Comment by htpcBeginner** [comment]
> I sometimes see this error in the Traefik log: `time="2022-01-05T13:01:01Z" level=error msg="Error renewing certificate from LE: {mydomain.eu [*.mydomain.eu]}, error: one or more domains had a problem:\n[*.mydomain.eu] time limit exceeded: last error: NS wanda.ns.cloudflare.com. returned REFUSED for _acme-challenge.mydomain.eu.\n[mydomain.eu] time limit exceeded: last error: NS mark.ns.cloudflare.com. returned REFUSED for _acme-challenge.mydomain.eu.\n" providerName=dns-cloudflare.acme` How can I fix it? Increase the time limit somewhere?

Thatis verify limited info. You need to show what happens in the log before that.

**Comment by PSJMcNeill** [comment]
I solved this on my end. I host mine on a remote server, needed to open additional ports to allow the Certificate retrieval to work. Then closed the ports again after.

**Comment by htpcBeginner** [comment]
@PSJMcNeill which port did you open and close? Only ports 80 and 443 are needed to be exposed for traefik. So i am curious + it would be nice for others to know and not wonder what you did.

**Comment by PSJMcNeill** [comment]
Unfortunately I can't remember at all. I just remember I eventually found logs that were timing out and it indicated a an address and port it was timing out on. Opening up the firewall solved it instantly.

**Comment by htpcBeginner** [comment]
Thanks for reporting back. Closing this thread.

**Comment by Raegedoc** [comment]
You gave me a hint where was the problem... if using secrets, do not forget to append "_FILE" at the end of "CF_API_EMAIL" and "CF_API_KEY".

Something like :

environment:
  - CF_API_EMAIL_FILE=/run/secrets/TRAEFIK-CF_API_EMAIL
  - CF_API_KEY_FILE=/run/secrets/TRAEFIK-CF_API_KEY

**Comment by chupacabra71** [comment]
i'm struggling with this in docker swarm.  i have the following in my compose file: 

```
    secrets:
      - CF_API_EMAIL
      - CF_DNS_API_TOKEN
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/CF_API_EMAIL
      - CF_DNS_API_TOKEN_FILE=/run/secret/CF_DNS_API_TOKEN
```

and using secrets in docker i declare this globally:

```
secrets:
  CF_API_EMAIL:
    external: true
  CF_DNS_API_TOKEN:
    external: true
```

but when i look at the environment variables of the container i see this: 

```
HOSTNAME=e8fe5e58428a
SHLVL=1
HOME=/root
TERM=xterm
CF_DNS_API_TOKEN_FILE=/run/secret/CF_DNS_API_TOKEN
CF_API_EMAIL_FILE=/run/secrets/CF_API_EMAIL
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```
