### ISSUE TITLE
Websocket connection fails

### ISSUE THREAD

**Issue by robflate** [htpcBeginner/docker-traefik#23]
I noticed you have xTeVe in `docker-compose-t2-obsolete.yml`. When you were using it, did you ever get round the `No websocket connection to xTeVe could be established` browser error when connecting to `xteve.domain.com/web`. It works if you got to `IP:PORT/web`.

All I could find was to add;

`traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https`

but I can't work out how to format it to fit in the Traefik v2 `rules/middlewares.toml` file or if it will even help.

Link (https://community.containo.us/t/how-to-make-websockets-work-with-traefik-2-0-setting-up-rancher/1732)

**Comment by robflate** [comment]
No longer an issue with xTeVe

**Comment by xFinrod-Felagundx** [comment]
@robflate how did you fix this? I am seeing the same issue.
