### ISSUE TITLE
Traefik using default cert

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#24]
All of a sudden traefik isnt working when going to my top level domain i.e. example.com it gives a cert warning issue when you inspect the cert its  common name is 'CN=TRAEFIK DEFAULT CERT' whereas all the subdomains which operate on the *.example.com are all fine and work through cloudflare. I have regenereated the acme json and it is still doing this. I dont understand why this is happening as it has been working until today.

**Comment by Joeharrison94** [comment]
This is the traefik log for when you try to visit the domain, I have changed only the WAN IP and domain name for security reasons

today at 3:26 PM time="2020-04-29T14:26:14Z" level=debug msg="Serving default certificate for request: \"example.com\""
today at 3:26 PM time="2020-04-29T14:26:15Z" level=debug msg="http: TLS handshake error from x.x.x.x:59639: remote error: tls: bad certificate"

**Comment by adradloff** [comment]
Does your acme.json show both certificates?
example.com and *.example.com

**Comment by Joeharrison94** [comment]
> Does your acme.json show both certificates? example.com and *.example.com

In my traefik 2 acme JSON at the bottom it states certificates: null

**Comment by Joeharrison94** [comment]
![Screenshot_20200429_183019](https://user-images.githubusercontent.com/53116754/80627258-82ccea80-8a47-11ea-9419-35419f00b3cc.jpg)

**Comment by adradloff** [comment]
looks like you may need to delete the contents and regenerate it by uncommenting out 
- "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" and building the traefik container.

**Comment by Joeharrison94** [comment]
That's what I did I have cycled it twice now the wildcards work but not the top level :(

**Comment by Joeharrison94** [comment]
Does your traefik 2 acme have certs at the bottom

**Comment by adradloff** [comment]
mine has this. which is after the private key.
  
    "Certificates": [
      {
        "domain": {
          "main": "domain.com",
          "sans": [
            "*.domain.com"

**Comment by Joeharrison94** [comment]
I have recreated the SSL as you said to and still nothing ?

**Comment by Joeharrison94** [comment]
The only thing I can think of that has changed is that I created a new API key for cloudflare ddns but left the global key in the config? Can't see how that would break it though

**Comment by Joeharrison94** [comment]
Fixed it by removing the image bloody hell this things buggy
