### ISSUE TITLE
Synology Firewall Issue

### ISSUE THREAD

**Issue by thibaudbrg** [htpcBeginner/docker-traefik#271]
Hello, I configured a Docker-traefik-Cloudflare setup with many applications (authelia sonarr radarr etc.. etc...) and everything works without problem BUT during all these configuration steps, I had disabled the synology firewall to make things easier.

Today I want to reactivate it but I don't know which ports to open to allow access to everything.

I searched everywhere on the web but without success. Also I tried several port openings (`80`, `443`, `8080`) but I not even have access to the traefik dashboard.

Which ports do I have to open? Thanks in advance.

**Comment by Maynardnaze** [comment]
80 443 8080 for dashboard. Do a port check too see

**Comment by thibaudbrg** [comment]
I was able to solve my problem. I didn't think about adding all the networks used by docker in the firewall en plus de 80 443 et 8080 pour traefik.
