### ISSUE TITLE
Plex Only Showing Player and Not Accessible Outside Network

### ISSUE THREAD

**Issue by zsanders61** [htpcBeginner/docker-traefik#275]
I'm having a a couple issues getting Plex to work in a docker container with Traefik. I've followed the Traefik2 tutorial on smarthomebeginner, and I'm able to reach the dashboard. However, whenever I try to access my plex server outside of my network, I get a 401 unauthorized access error. Whenever I try to access my Plex server inside of my network, I am only ably to see the player, and am unable to manage the container as a server. Below I have attache the Plex portion of my yaml file.

  # Plex - Media Server
  plexms:
    image: plexinc/pms-docker:public
    container_name: plexms
    restart: "no"
    networks:
      - t2_proxy
    #devices:
      #- /dev/dri:/dev/dri # for harware transcoding
    security_opt:
      - no-new-privileges:true
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      #- "1900:1900/udp" # conflicts with xTeVe
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      #- "$PLEX_WEB_TOOLS_PORT:33400"
    volumes:
      - $DOCKERDIR/appdata/plexms:/config
      - $DATADIR/downloads:/data/downloads
      - $DATADIR/movies:/data/movies
      - $DATADIR/shows:/data/shows
      #- /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
      # Optional. See why the folders below are mounted as volumes https://github.com/htpcBeginner/docker-traefik/discussions/147
      #- $DATADIR/docker/appdata/plexms/Library/Application Support/Plex Media Server/Cache:/config/Library/Application Support/Plex Media Server/Cache
      #- $DATADIR/docker/appdata/plexms/Library/Application Support/Plex Media Server/Metadata:/config/Library/Application Support/Plex Media Server/Metadata
      #- $DATADIR/docker/appdata/plexms/Library/Application Support/Plex Media Server/Media:/config/Library/Application Support/Plex Media Server/Media
    environment:
      TZ: $TZ
      HOSTNAME: "ZSAPlex"
      PLEX_CLAIM: "claim-aVPgYxdYshXkEHJZZwxG"
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: http://$SERVER_IP:32400/
      #VIRTUAL_HOST: proxplex.$DOMAINNAME
      #VIRTUAL_PORT: 443
      #VIRTUAL_NETWORK: t2_proxy
    #secrets:
      #- plex_claim
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plexms-rtr.entrypoints=https"
      - "traefik.http.routers.plexms-rtr.rule=Host(`plex.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.plexms-rtr.middlewares=chain-no-auth@file"
     ## HTTP Services
      - "traefik.http.routers.plexms-rtr.service=plexms-svc"
      - "traefik.http.services.plexms-svc.loadbalancer.server.port=32400"

**Comment by zsanders61** [comment]
It looks like I accidentally copy and pasted the yaml from someone else's issue. I've edited my original post with the correct yaml.

**Comment by zsanders61** [comment]
I'm still having the issue. I can can access Plex outside my network now after I added the advertise IP line, but I still only see the player. I've tried several claim tokens and have not been able to get it working.

**Comment by gerardsyd** [comment]
@zsanders61 did you get this fixed? For advertise IP, are you using the internal IP on traefik for plex or the internal IP of the server or the external IP of the server? Thanks!
