### ISSUE TITLE
no configuration file provided: not found

### ISSUE THREAD

**Issue by medbrosis** [htpcBeginner/docker-traefik#283]
Hello Anand Your Ultimate Traefik Docker Compose Guide [2022] was excellent. I've tried multiple times to set up traefik with great care, but I've never been able to do it. I receive the error "no configuration file provided: not found" when I run docker compose up. How can we fix this?

**Comment by htpcBeginner** [comment]
Sorry late reply. Join our discord and ask for support if you still need it.
