### ISSUE TITLE
Mismatching values on chain-basic-auth

### ISSUE THREAD

**Issue by petrowsky** [htpcBeginner/docker-traefik#286]
[chain-auth-basic@file](https://github.com/htpcBeginner/docker-traefik/blob/7442900972bbd24d20fec220444ec31a7016448b/docker-compose-t2.yml#L245) at line 245 does not match **chain-basic-auth:** [found here](https://github.com/htpcBeginner/docker-traefik/blob/7442900972bbd24d20fec220444ec31a7016448b/appdata/traefik2/rules/cloudserver/middlewares-chains.yml#L12)

You need to change it to **chain-basic-auth@file** (switch the words "auth" and "basic") in order to not generate an error in traefik.

**Comment by htpcBeginner** [comment]
Ah! Thanks for pointing it out. I fixed it. It will be pushed in the next  commit.
