### ISSUE TITLE
Wrong folder in 'touch' description

### ISSUE THREAD

**Issue by Bockiii** [htpcBeginner/docker-traefik#293]
Hi,

you're telling the user to touch a new file in $DOCKERDIR/traefik2, where it needs to be $DOCKERDIR/appdata/traefik2

https://github.com/htpcBeginner/docker-traefik/blob/1c22d147ea11ea1c9143ddc7961392673e60ef31/docker-compose-t2.yml#L129

**Comment by htpcBeginner** [comment]
Good catch. Thanks. Fixed.

https://github.com/htpcBeginner/docker-traefik/commit/3731045c70f1fa305324c0deb8b292001a9461f5

**Comment by Bockiii** [comment]
Without opening a new one, this is also wrong:

https://github.com/htpcBeginner/docker-traefik/blob/1c22d147ea11ea1c9143ddc7961392673e60ef31/docker-compose-t2.yml#L211

      - $DOCKERDIR/logs/cloudserver/traefik:/logs # for fail2ban or crowdsec

Should be

      - $DOCKERDIR/appdata/traefik2/logs/cloudserver/traefik:/logs # for fail2ban or crowdsec
