### ISSUE TITLE
Linuxserver v Codercom VSCode

### ISSUE THREAD

**Issue by robflate** [htpcBeginner/docker-traefik#30]
Can  I ask why you went back to the codercom container for VSCode and obsoleted the linuxserver one? Was it because the Linuxserver one chowns the contents of whatever volume you mount which is sometimes not what you want, say for instance if you mounted your `/configs` folder?

Just curious because other than the chown behaviour the linuxserver one seems slightly easier to run and easier to setup ssh keys.

**Comment by htpcBeginner** [comment]
I went back and forth between the two. I am new to VSCode.

I struggled with both. I added folders and saved a workspace. When I reloaded saved workspaces both images caused vscode window to keep reloading. May be I am doing something wrong. 

I liked Linuxserver's and it might be better. I do not know. 

On codercom's I mapped my code folders inside /home/coder/ and it automatically picked up everything. Even the sessions are saved and restored as they are supposed. So I just started rolling with it.

If Linuxserver's images own the mounted folders (PUID:PGID) then it might actually be what I would like to have. 

Could you please explain "easier to run" and "easier to setup SSH keys". I just added SSH keys to codercom's to ssh into my other systems and it was a breeze. Created the .ssh folder in /home/coder/ and copied over config and the keys and I was ready to roll.

I am pulling the other co-auther of the post @CVJoint.

**Comment by robflate** [comment]
Strangely, our experiences are the exact opposite. I had lots of trouble getting codercom's version to restore sessions and never really managed to sort out the permissions issues I was having. I'd have a file owned by `user:docker` outside the container and despite sending the same PUID and PGID env variables in the compose file I'd constantly get permission errors when saving in VSCode. I also had trouble setting up ssh keys with github although it worked in the end.

In contrast, the Linuxserver version just worked out of the box including sessions, ssh, github and permissions. My only trouble with it is that it chowns the contents of whatever volume you mount which for the most part is useful but in some circumstances might be undesirable. For instance, mounting a containers `config` folder which may contain specific permissions (e.g. xTeVe runs Guide2Go as an unprivileged user and the Linuxserver version changes ownership causing Guide2Go to fail with permission errors).

I should clarify both those rather general statements I made. They both just apply to my experience with the 2 different versions rather than any deep understanding of the differences. Apologies.

**Comment by htpcBeginner** [comment]
Omg, i just noticed that all my folders lost their permissions :-(. I am suspecting it is the linuxserver's image changing the permissions of the folders i mapped :-(. I am in a mess right now.

**Comment by robflate** [comment]
It's definitely LSIO VSCode. If you change a files permission (in a volume mounted in VSCode) and then `up` VSCode, it changes the permissions back to whatver VSCode has in the env variables. I only noticed when xTeVe failed to run some cron jobs. I think I fixed it by removing LSIO VSCode and `--force-recreate` on all the other containers. The ones that have specific permissions seemed to chown the folders back. Your mileage may vary.

**Comment by htpcBeginner** [comment]
Did how did you use force recreate. Can please elaborate?

**Comment by robflate** [comment]
Sorry, I just meant to recreate all the containers which can be achieved even if their configuration and image haven't changed by using the flag `--force-recreate` flag when using `docker-compose up`.

`docker-compose up --force-recreate`

Or for an individual container;
`docker-compose up -d --force-recreate xteve`

[Reference](https://docs.docker.com/compose/reference/up/)

**Comment by htpcBeginner** [comment]
Yeah i UPed the stacked with force-recreate. 

Anyway, I am up and running for now. Closing this issue. I am sticking with Codercom's image for now.
