### ISSUE TITLE
Using Cloudflare free origin certs

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#33]
Hello,

Would it be possible to add a section in on how to use the free origin SSL certs available from cloudflare rather than using let's encrypt please

**Comment by htpcBeginner** [comment]
I have not used CF origin certs. How are they different than using your own self-signed certs? If they are not different, then Traefik already provides a self-signed cert.

The only difference I can see is you can enable "Full/Strict" SSL in Cloudflare, whereas with self-signed it has to be "Ful". The encryption level is not significantly different.
