### ISSUE TITLE
{APPNAME}_API_KEY Undefined

### ISSUE THREAD

**Issue by android-808** [htpcBeginner/docker-traefik#38]
RADARR_API_KEY, SONAR_API_KEY etc. are currently only mentioned in the compose file.  Without corresponding entry in .env, or .env.example here, Traefik seems to route all traffic to one of the bypass routers.  The host rule causes  a match due to the blank env var for all domains as the rule doesn't specify against what domain to run the check.

Would it be worth adding a note to the compose file requiring it first to be run with bypass disabled to gather the API keys and entries in .env.example for the keys.

**Comment by tombomb** [comment]
https://github.com/htpcBeginner/docker-traefik/pull/39

**Comment by htpcBeginner** [comment]
@tombomb Thanks.
