### ISSUE TITLE
Update readme for t2

### ISSUE THREAD

**Issue by ravensorb** [htpcBeginner/docker-traefik#4]
Any chance you could do a quick update of the readme for getting things up and running with traefix2? 

Example: In the docker compose file there is a reference to a t2_proxy network however there is no information on how it is setup?

**Comment by htpcBeginner** [comment]
in the docker-compose file for t2, there is this line at the top under traefik service:

`docker network create --gateway 192.168.90.1 --subnet 192.168.90.0/24 t2_proxy`

This creates the t2_proxy network.

I will work on a guide in the coming weeks.

**Comment by ravensorb** [comment]
Cool!  As and added note, I see in the t2 there variables that are not in the env file (ex: radarr api key, unifi, etc).  Are these new things you are adding support for?  Do you have an example of a working env file?
