### ISSUE TITLE
Replace Ouroborus with Watchtower

### ISSUE THREAD

**Issue by Akruidenberg** [htpcBeginner/docker-traefik#40]
No longer in development.

See

https://github.com/pyouroboros/ouroboros

**Comment by htpcBeginner** [comment]
I will switch over at some point. It is in the plan. too bad it does not support telegram notification yet.

**Comment by proddy** [comment]
it does right? use https://github.com/caronc/apprise/wiki/Notify_telegram

**Comment by tombomb** [comment]
looks like watchtower can send telegram notifications using containrrr/shoutrrr it has the downside of using another continer 
https://containrrr.github.io/watchtower/notifications/
https://containrrr.github.io/shoutrrr/services/overview/

**Comment by htpcBeginner** [comment]
I will switchover at some point. Just not a priority for me at this point as ouroboros works.

**Comment by gzecchi** [comment]
Hello @tombomb,
with commit 6e100525769bb2f10e73e5eb23048380d3cbc5ae Ouroboros has been replaced by Watchtower.
GZ

**Comment by htpcBeginner** [comment]
https://github.com/htpcBeginner/docker-traefik/commit/6e100525769bb2f10e73e5eb23048380d3cbc5ae
