### ISSUE TITLE
bazarr dosent use X-Api-Key

### ISSUE THREAD

**Issue by tombomb** [htpcBeginner/docker-traefik#44]
Didn't do a pull request for this one, I can if you want. I'm going though now and disabling all my ports on my stack and just using the routes though traefik and all was working till I hit bazarr.  They don't send the api call with the X-Api-Key. I fixed my stack by changing the bypass lines from 

```
- "traefik.http.routers.sonarr-rtr-bypass.rule=Headers(`X-Api-Key`, `$SONARR_API_KEY`)"
```
to
```
- "traefik.http.routers.sonarr-rtr-bypass.rule=Headers(`X-Api-Key`, `$SONARR_API_KEY`) || Query(`apikey`, `$SONARR_API_KEY`)"
```

That way its still locking out the url unless they have the right key, did this for sonrr and radarr and now everything is hunkydory.

**Comment by htpcBeginner** [comment]
Thanks! I will make changes based on this.

**Comment by robflate** [comment]
@tombomb Have you disabled all your ports? If so, how are you communicating between apps? Apologies if I've misunderstood.

**Comment by tombomb** [comment]
@robflate so for your docker config you can comment out the ports part like this 
```
    # ports:
    #   - "$SONARR_PORT:8989"
```
and then just use the traefik router with 

```
- "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"
```

that will let you access the it while locking down the port, doing this you can turn off auth on the apps and make sure that they are accessed through authelia and all the auths that you have.

**Comment by robflate** [comment]
Quick update. It was a coincidence. I still have the issue #35
