### ISSUE TITLE
Cloudflare Proxied or DNS-only?

### ISSUE THREAD

**Issue by ptoulouse** [htpcBeginner/docker-traefik#47]
Missing from the traefik2 article or from the Readme is whether or not the proposed setup is working with Cloudflare DNS entries in Proxy or DNS-only mode.

**Comment by flebel** [comment]
Either will work.

**Comment by ptoulouse** [comment]
Without exceptions? I tested a few easy ones and they work, but I am more concerned by Plex and Nextcloud where you might break something and have a hard time figuring out.

**Comment by htpcBeginner** [comment]
I recently started to proxy all my traffic. I use CF companion to auto create DNS entries for services. For plex or any media server for that matter, you will need to add by pass rules in cloudflare to avoid caching. 

I will try to write a separate guide on cloudflare-traefik settings.

**Comment by htpcBeginner** [comment]
this guide is now published: https://www.smarthomebeginner.com/cloudflare-settings-for-traefik-docker/

**Comment by randomodbuild** [comment]
I am having some trouble getting nextcloud to work. I tried the TCP passthrough that your website suggested but I always get a privacy warning when trying to access nextcloud. NET::ERR_CERT_AUTHORITY_INVALID
When I click on the certificate it is just the linuxserver certificate. How can I fix this?
