### ISSUE TITLE
Authelia not picking up configuration file

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#50]
I have setup the compose yml, config file and user file as per authelias instructions and your examples but im getting 

time="2020-06-17T11:40:51+01:00" level=error msg="Unable to find config file: /config/configuration.yml"
time="2020-06-17T11:40:51+01:00" level=error msg="Generating config file: /config/configuration.yml"
time="2020-06-17T11:40:51+01:00" level=error msg="Generated configuration at: /config/configuration.yml"

I am using the eaxact compose you are using to map them and I have checked the path manually and it shoudl be fine but it cant see it even ran chmod 777 and alters the file perms

**Comment by Joeharrison94** [comment]
I also dont think it can connect to mariadb, I have put in "mariadb" as this is the container name and I dont use IP addresses in my t2 network is this what you have done?

**Comment by Joeharrison94** [comment]
I have fixed the issue with the conf fille by updating the volumes in the compose yml to 

      - $USERDIR/docker/authelia/authelia:/var/lib/authelia
      - $USERDIR/docker/authelia:/config:ro
      - $USERDIR/docker/authelia/users_database.yml:/etc/authelia/users_database.yml

the only issue now is it cant initialise the myswl db it is saying 

time="2020-06-17T12:50:54+01:00" level=fatal msg="Unable to initialize SQL database: Unable to create table user_preferences: Error 1045: Access denied for user '**sensitive data removed**'@'authelia.t2_proxy' (using password: YES)" stack="github.com/authelia/authelia/internal/storage/mysql_provider.go:72 NewMySQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:76               startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:121              main.func1\ngithub.com/spf13/cobra@v0.0.7/command.go:842                       (*Command).execute\ngithub.com/spf13/cobra@v0.0.7/command.go:943                       (*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.7/command.go:883                       (*Command).Execute\ngithub.com/authelia/authelia/cmd/authelia/main.go:138              main\nruntime/proc.go:203                                                main\nruntime/asm_amd64.s:1373                                           goexit"

**Comment by rondobohrens** [comment]
Hi, 

I just fixed this, you need to change the mapped directories under volumes in the docker compose file: 

https://github.com/authelia/authelia/releases <-- Refer to breaking in 4.20

`authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    networks:
      - t2_proxy
    # ports:
    #   - "9091:9091"
    volumes:
      - $USERDIR/authelia/authelia:/var/lib/authelia
      - $USERDIR/authelia/configuration.yml:/config/configuration.yml
      - $USERDIR/authelia/users_database.yml:/config/users_database.yml
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"`

**Comment by Joeharrison94** [comment]
Thank you this seems to get it up and running but when I login and click the resiter link to setup the otp it gives a link and says failed to generate the code to register your device ? any thoughts

**Comment by Joeharrison94** [comment]
The nzb360 app is working for my services using the bypass so I dont think its a config issue but it wont seem to allow me to create my otp :/ @rondobohrens

**Comment by Joeharrison94** [comment]
totp:
  issuer: authelia.com
  period: 30
  skew: 1

thats the totp section

**Comment by Joeharrison94** [comment]
also worth noting i have registered my fido key which worked well and allows me access just the totp that wont work at all

**Comment by rondobohrens** [comment]
The topt file looks correct.

Did you set all of your secrets (e.g., using https://www.grc.com/passwords.htm) correctly under 
jwt_secret
and 
secret (under the session section)? 

And if that does not help, could you provide the authelia logs from the docker container?

**Comment by htpcBeginner** [comment]
I bet this is a secrets issue. Please provide your full config.

**Comment by Joeharrison94** [comment]
It was that the device I was using to activate the link was different to the device issues the email, I have it working now:) 

Last couple of things I promise.

Is there any way to get a bypass for the tautulli app I tried the same method as for sonarr radarr and sab but it doesnt like it.

 Is there any reason I should swap to mariadb and try again rather than sticking to the local db file.

Do you use duo if so is it any good.

**Comment by htpcBeginner** [comment]
Just adding that as of v4.2 of Authelia volume mappings have changed: https://github.com/authelia/authelia/blob/master/BREAKING.md#breaking-in-v4200

This is a breaking change and will need updating the volume mappings.
