### ISSUE TITLE
Tautulli App Bypass Authelia

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#52]
Is there any way to get a bypass for the tautulli app I tried the same method as for sonarr radarr and sab but it doesnt like it.

Also is there any reason I should swap to mariadb and try again rather than sticking to the local db file for authelia?

Thanks in advance

**Comment by inquam** [comment]
If that doesn't work you might not have a rule that catches the request in question? You have placed it above the first HTTP router of Tautulli so it has a chance to catch and bypass? If you want authelia to ignore the entire app you could just remove it as a middleware for that container.  You could also add rules in authelia's config file.

Post what you have and it might be a bit clearer exactly what you are trying to accomplish.

**Comment by Joeharrison94** [comment]
Thanks for the response, so I have tried adding in this into the access control

 - domain: "tautulli.mydomain.co.uk"
      policy: bypass
      subject: "group:admins"
      resources:
      - "^/api/.*$"              

then added this into my traefik labels

#      - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
#      - "traefik.http.routers.tautulli-rtr-bypass.rule=Headers(`X-Api-Key`, `$TAUTULLI_API_KEY`) || Query(`apikey`, `$TAUTULLI_API_KEY`)"
#      - "traefik.http.routers.tautulli-rtr-bypass.priority=100"

but to no avail it just crashes the app

**Comment by inquam** [comment]
Not that you do not need both. Either you have the container get redirected to Authelia in your docker config and then in Authelia handle the bypass or you handle the bypass without involving Authelia by bypassing the middleware for a given request.

Regarding your Authelia config. If you have a subject in your access control rule of admins then it would need to know you are an admin. Only way for it to know that is for you to have signed in with an admin user. So you would probably not want to have that part there if what you are trying to achieve is to not have to authenticate. Not that any rule to bypass would have to come before any rule that would do anything else because the first rule to match seems to be used.

Regarding doing this in docker you would have to have the bypass catch before the one that redirect you to the Authelia middleware. Something like this perhaps (not testet)

```
labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr-bypass.rule=Query(`apikey`, `$TAUTULLI_API_KEY`)
      - "traefik.http.routers.tautulli-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
      - "traefik.http.routers.tautulli-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
```

Note that the _tautulli-rtr-bypass_ passes through the _chain-no-auth@file_ middleware.
No matter the route I would probably go the way of including the api key in the rule since that will make anyone hitting the rule but not supplying the correct key not bypass authentication. So even if you do something like 

```
labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
      - "traefik.http.routers.tautulli-rtr.priority=100"
      ## Middlewares
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
```

to have it always go through Authelia I would in the Authelia config to bypass the authentication include the api key.

```
domain: "tautulli.mydomain.co.uk"
policy: bypass
resources:
  "^/api/v2\?apikey=ENTER_API_KEY_HERE.*$"
```

Not quite sure about which regex style Authelia uses but I'm guessing ? should be escaped :)

**Comment by Joeharrison94** [comment]
Thanks for the feedback I am trying to get it done in the authelia conf file but it doesnt like escaping the ? symbol

**Comment by Joeharrison94** [comment]
I dont think this is going to work for this app, the app is using a device token in the settings not the actual api key

**Comment by htpcBeginner** [comment]
Use this to enable bypassing for Tautulli App (Credit: @CVJoint)

`      - "traefik.http.routers.tautulliAPI-rtr.rule=HeadersRegexp(`User-Agent`, `Tautulli`)"`

Please report back to close the issue.

**Comment by Joeharrison94** [comment]
> 
> 
> Use this to enable bypassing for Tautulli App (Credit: @CVJoint)
> 
> ` - "traefik.http.routers.tautulliAPI-rtr.rule=HeadersRegexp(`User-Agent`, `Tautulli`)"`
> 
> Please report back to close the issue.

Thanks for the label, is this to be used inconjunction with the above

**Comment by Joeharrison94** [comment]
Got a working tautulli api authelia bypass you need you update the query to use the device token id not the global api that is given by tautulli, you get this from the add a new device screen then use the following.

      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr-bypass.rule=Headers(`X-Api-Key`, `$TAUTULLI_DEVICE_KEY`) || Query(`apikey`, `$TAUTULLI_DEVICE_KEY`)"
      - "traefik.http.routers.tautulli-rtr-bypass.priority=100"
      ## HTTP Routers
#      - "traefik.http.routers.tautulliAPI-rtr.rule=HeadersRegexp(User-Agent, Tautulli)"      
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
      - "traefik.http.routers.tautulli-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"

**Comment by bpersino** [comment]
@Joeharrison94, 
I have used exactly what you posted above, but could use your assistance.

`    - "traefik.enable=true"
    ## HTTP Routers Auth Bypass
    - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
    - "traefik.http.routers.tautulli-rtr-bypass.rule=Headers(`X-Api-Key`, `$TAUTULLI_DEVICE_KEY`) || Query(`apikey`, `$TAUTULLI_DEVICE_KEY`)"
    - "traefik.http.routers.tautulli-rtr-bypass.priority=100"
    ## HTTP Routers
    - "traefik.http.routers.tautulli-rtr.entrypoints=https"
    - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
    - "traefik.http.routers.tautulli-rtr.priority=99"
    ## Middlewares
    - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file"
    - "traefik.http.routers.tautulli-rtr.middlewares=chain-authelia@file"
    ## HTTP Services
    - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
    - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc"
    - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"`    

For some reason, the Tautulli app bypass is not working.  Its still hitting authelia for some reason, please see screenshot below.  I have successfully bypassed other apps, so I know authelia bypass works.

![Screenshot_20200629-095555_Tautulli Remote](https://user-images.githubusercontent.com/12070082/86021750-0dea4280-b9ef-11ea-9cc0-196a81655c86.jpg)
`

**Comment by Joeharrison94** [comment]
Are you storing your API key or the device id that you get from the tautulli mobile app section in the settings ? ---- On Mon, 29 Jun 2020 16:02:06 +0100  notifications@github.com  wrote ----
@Joeharrison94,
I have used exactly what you posted above, but could use your assistance.
    - "traefik.enable=true" ## HTTP Routers Auth Bypass - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https" - "traefik.http.routers.tautulli-rtr-bypass.rule=Headers(X-Api-Key, $TAUTULLI_DEVICE_KEY) || Query(apikey, $TAUTULLI_DEVICE_KEY)" - "traefik.http.routers.tautulli-rtr-bypass.priority=100" ## HTTP Routers - "traefik.http.routers.tautulli-rtr.entrypoints=https" - "traefik.http.routers.tautulli-rtr.rule=Host(tautulli.$DOMAINNAME)" - "traefik.http.routers.tautulli-rtr.priority=99" ## Middlewares - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file" - "traefik.http.routers.tautulli-rtr.middlewares=chain-authelia@file" ## HTTP Services - "traefik.http.routers.tautulli-rtr.service=tautulli-svc" - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc" - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
For some reason, the Tautulli app bypass is not working.  Its still hitting authelia for some reason, please see screenshot below.  I have successfully bypassed other apps, so I know authelia bypass works.

`

**Comment by bpersino** [comment]
I was able to get it working,  my indentation was incorrect for the labels.

**Comment by Joeharrison94** [comment]
Good I'm glad, out of interest do you use it for any other apps I'm keen to find some new services that have companion apps I use nzb360 but they doesn't seem to work half the time (not the API key but the app in general) ---- On Mon, 29 Jun 2020 23:00:49 +0100  notifications@github.com  wrote ----

I was able to get it working,  my indentation was incorrect for the labels.

**Comment by bpersino** [comment]
The only other app I use is also nzb360, but I don’t have any issues with that app working, although I don’t really use it much.  I guess I just like getting notifications from the app when something new downloads.
