### ISSUE TITLE
Lazy --> Calibre --> Calibre Web, Assisstance

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#56]
Do you have any guides on how to get this setup so they all work together I have fathomed most of it out but seem to be having issues with calibre and calibre web and would like to know in particular how you have configured it.

**Comment by robflate** [comment]
What's not working? A few things to check for basic functionality;

### Calibre
- Create a new library in `/Books` or whatever volume you have mapped. Call it `Books`.
- Preferences > Sharing over the net > Users = Add user
- Preferences > Sharing over the net > Main = Port = `8081`, Require username = tick, Run server = tick, click Start Server

### LazyLibrarian
- Settings > Processing > Calibre > Calibredb import program: = `/usr/bin/calibredb`
- Settings > Processing > Calibre > Calibre Server: = `http://calibre:8081/#Books` (Change after # to name of Calibre Library) (Save page before testing)
- Settings > Processing > Calibre > Calibre Username/Calibre Password: = Add the user you setup in Calibre

### Calibre-Web
- Basic Configuration > Location of Calibre database = `/data/media/Books`
- Basic Configuration > Use calibre's ebook converter = Tick, Path to convertertool = `/usr/bin/ebook-convert`

After that works, you'll want to setup;

- Goodreads API in LL to auto download books when you 'Like' them on the Goodreads app.
- Kindle email in CW
- Magazines, Comics and Audiobooks in LL
- OPDS servers in LL and CW to use 3rd party apps for reading like Marvin

**Comment by Joeharrison94** [comment]
Thanks for this so 

I am using tha same docker compose sections as in the example but with my own bind mounts for storage.

I am having issues with lazy library in the "Calibredb import program" thats set to /usr/bin/calibredb and it connects but says "database READ failed or database is empty" so this may be ok for now.

So I have the downloads complete in Sab into /mnt/media/SABnzbd/Complete/Lazy which is then picked up by Lazy and it puts then Lazy polls that and sorts them into either /mnt/media/Books/eBooks or /mnt/media/Books/Audio Books

What I dont get is how Calibre is fitting in as I have set the Calibre Library to /mnt/media/Books/Calibre Library but I cant get it to work at all and Calibre web wont connect to the db  at all it says it doesnt exist.

**Comment by Joeharrison94** [comment]
I think my issue is that the downloads complete into the aforementioned /ebooks and /audio books and calibre is in /calibre library and Im not sure if they should be like that. Also when I try create a library in calibre it and place it in /ebooks or / audio books it gives me a permission denied even though the bind mounts are set with rw permissions.

**Comment by robflate** [comment]
My eBooks and Calibre library are in the same folder. Magazines, Audiobooks and Comics are in their own separate folders (I only have eBooks in Calibre/Calibre-Web) so I also uncheck `Magazines/Comics inside book folder` in LL .

The only thing I have in my Calibre compose file that isn't in this stack;

```
environment:
  UMASK_SET: 002
```

maybe that might fix your permissions issue?

Other things to check;

- In LL > Settings > Processing > Calibre > `Use calibredb to import ebooks` = ticked
- In LL > Settings > Processing > Folders > Download Directories: = I have my usenet/torrent downloaders completed folders here, e.g. `/data/usenet/completed/Books,/data/torrent/complete/Books,/data/torrent/complete`

**Comment by htpcBeginner** [comment]
pretty much covered in the above responses. I also have my mask at 002. Just pushed the update to the git. I have everything working but i am still fine tuning....will write a guide after it is running smoothly.

**Comment by Joeharrison94** [comment]
Ok so how do you have the books and the calibre library in the same folder as it states it must be empty to create the library ?

**Comment by Joeharrison94** [comment]
Ther are both in the same root folder ie
/mnt/media/Books/
           ------------/Calibre Library
           ------------/eBooks
           ------------/Audio Books

**Comment by Joeharrison94** [comment]
I have managed to get it working to have calibre libray in the same folder now as eBooks but I get this from LL

Postprocessing for 'The Guardians - John Grisham' has failed: 'calibredb rc 1 from /usr/bin/calibredb'

This happens for every single book

**Comment by robflate** [comment]
When I click `Test calibredb` I get;
```
calibredb ok, version 4.19
Database READ ok
Database WRITE ok
```

Sounds like you haven't entered the correct info in the `Settings > Processing > Calibre` section of LL. In Calibre, make sure you've added a user, enabled `Sharing over the net` and started the Server as below;

1. In Calibre `Preferences > Sharing over the net > Users = Add a user/password`
2. In Calibre `Preferences > Sharing over the net > Main = Port = 8081, Require username = tick, Run server = tick, click Start Server`
3. In LL `Settings > Processing > Calibre > Calibre Server: = http://calibre:8081/#Books`. Change `Books` to whatever you named your Calibre Library, check your Calibre container is named `calibre` and check you set the Calibre `Sharing over the net` Port to 8081.
4. In LL `Settings > Processing > Calibre > Calibre Username: = Enter the Calibre username you created in step 1.
5. In LL `Settings > Processing > Calibre > Calibre Password: = Enter the Calibre password you created in step 1.

Note: You have to click save in LL after making changes to the Calibre section before you can click `Test calibredb`.

Also, have you checked the issues at https://gitlab.com/LazyLibrarian/LazyLibrarian/ and the documentation at https://lazylibrarian.gitlab.io? The dev is very active and helpful.

**Comment by Joeharrison94** [comment]
Awesome I actaully managed to fix it with a restart must have altered a setting in the compose :) 

Last question now,  where do you put your downloads so it can be picked up and put into the calibre library I have basically got this
SAB -----> completes to  /mnt/media/SABnzbd/Complete/Lazy
LL   -----> picks up from /mnt/media/SABnzbd/Complete/Lazy
LL   -----> places ebooks in /mnt/media/Books/eBooks (Calibre Library is also in the root of this folder)
LL   -----> places audo books in /mnt/media/Books/Audio Books
Also have in the processing settings calibre books auto add dir the saome as the eBooks folder

Is that right ?

**Comment by robflate** [comment]
Read the LL documentation page to understand `Calibre Books Auto Add Directory` https://lazylibrarian.gitlab.io/config_processing/ (the LL documentation is very thorough). I leave this blank.

I use NZBGet and QBittorrent (and occasionally Transmission) so a bit different but I;

1. In LL `Settings > Processing > Calibre > Use calibredb to import ebooks` = ticked
2. In LL `Settings > Processing > Folders > Download Directories:` = I have my usenet/torrent downloaders completed folders here, e.g. `/data/usenet/completed/Books,/data/torrent/complete/Books,/data/torrent/complete`. The reason for 2 torrent folders is because QBittorrent uses folders so places completes in `Books` but Transmission does not so places completes in `complete`.

**Comment by Joeharrison94** [comment]
awesome thanks
