### ISSUE TITLE
404 Dashboard error with new Traefik2 setup

### ISSUE THREAD

**Issue by modem7** [htpcBeginner/docker-traefik#59]
Hi guys, 

I'm pretty sure this is an ID10T issue, but I've previously used Nginx, so not quite sure where to diagnose here!

First time setting up Traefik v2, and got a Dashboard 404 error.

I've tried curl https://192.168.0.6:8080/api/http/routers and get: 404 page not found

Here's my config: https://pastebin.com/KUpSPVAk

Inspect response: https://pastebin.com/MwYaDPik 

Here are the logs I currently have: https://pastebin.com/nR9cEzm1

I'm also getting 404 on https:// traefik. modem7. com.

![69fe1bf3841f34e92f5b3928723a056cf6881886](https://user-images.githubusercontent.com/4349962/85961400-19fbe300-b9a2-11ea-89c6-5f829d3d1a34.png)

I'm also seeing acme.json is still empty.

Any help for this muppet would certainly be appreciated!

Thank you

**Comment by htpcBeginner** [comment]
You have indentation issues:

`
    ports:
     - "80:80"
      - "443:443"
      - "8080:8080"
`

And your traefik logs points this out.

**Comment by htpcBeginner** [comment]
Plus you are using staging server, which I assume because you are still testing.

**Comment by modem7** [comment]
Heya, 

Yupper, the staging server is only because I'm still getting everything set up!

Regarding the indentation, it seems that's an odd pastebin glitch.

Here's my notepad++ SS:

![image](https://user-images.githubusercontent.com/4349962/86373155-fde69300-bc7a-11ea-99fa-3579a9325bfc.png)

**Comment by demartini** [comment]
Hi @modem7,

Use a yaml validator like (https://jsonformatter.org/yaml-validator) to check the code's indentation, this help a lot.

**Comment by modem7** [comment]
> 
> 
> Hi @modem7,
> 
> Use a yaml validator like (https://jsonformatter.org/yaml-validator) to check the code's indentation, this help a lot.

Hello, 

Thank you for the link. The only issue that was happening was with this line here:

`       - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)`

I notice that on github it's different than from the guide with it's formatting. 

Here are my latest files:
Traefik log:
https://pastebin.com/bFHMHhKk

Yaml:
https://pastebin.com/qAQX1CV0

![image](https://user-images.githubusercontent.com/4349962/86503562-4b601e80-bda7-11ea-8b0f-5783a95ef9f8.png)


Unfortunately still getting a 404 when attempting.

**Comment by Akruidenberg** [comment]
I have this also. Ik set version tag 2.2.1 and its working now!

**Comment by modem7** [comment]
> 
> 
> I have this also. Ik set version tag 2.2.1 and its working now!

Thanks for the reply! 

I gave that a try but unfortunately getting the same thing! 

I've even tried commenting out the staging server line to see if it was that, but still no go

**Comment by modem7** [comment]
> 
> 
> I have this also. Ik set version tag 2.2.1 and its working now!

Would you be able to paste your config in pastebin so I could see where I'm going wrong at all?

**Comment by randomodbuild** [comment]
I see this issue is closed, were you able to fix it @modem7 ?

**Comment by modem7** [comment]
> I see this issue is closed, were you able to fix it @modem7 ?

Sorry for the delay in replying! 

So in my particular case, it was because I was trying to run traefik on a macvlan which was screwing with things. Once I attached it to the bridge network, it worked perfectly.
