### ISSUE TITLE
Configuring and using a mariadb container with Guacamole & guacd

### ISSUE THREAD

**Issue by starrbuck68** [htpcBeginner/docker-traefik#6]
Thanks for all your work on this project!

This config file allows you to host the mariadb/mysql container on the docker machine and access it with Guacamole.

[guac.yml.txt](https://github.com/htpcBeginner/docker-traefik/files/4033404/guac.yml.txt)

**Comment by htpcBeginner** [comment]
Thanks. I just added mariadb to my stack today. Will move over guacamole to the new database soon.

**Comment by Presjar** [comment]
Hi, I believe if you are starting this process with fresh MariaDB and Guac, Guac is unable to create the GUAC_MYSQL_DATABASE. I had to manually create the guacamole ${GUAC_MYSQL_USER} and populate the database with the initdb.sql file here: https://elatov.github.io/2018/06/install-guacamole-on-docker/#configure-mariadb

**Comment by htpcBeginner** [comment]
i have explained this in detail here https://www.smarthomebeginner.com/install-guacamole-on-docker/
