### ISSUE TITLE
Redirection to Authelia Authentication Site not working

### ISSUE THREAD

**Issue by Derever** [htpcBeginner/docker-traefik#61]
When trying to access for example jackett.mydomain.com while **not being logged in**, I am redirected to:

`https://authelia.example.com/?rd=https%3A%2F%2Fjackett.mydomain.com%2FUI%2FDashboard`

Instead of the Authelia Authentication Site

Does anyone have a solution for that?

**Comment by beloso** [comment]
Did you change the address in the Authelia middleware?
Did you change the address in the Authelia configuration.yaml?

**Comment by Derever** [comment]
That was it!! I overlooked the middlewares.toml file lines where the authelia.example.com is specified. Thanks a lot!!
