### ISSUE TITLE
Question about disk partitions

### ISSUE THREAD

**Issue by attzonko** [htpcBeginner/docker-traefik#62]
First of all, I want to thank you for putting all this knowledge out there and documenting your set up. I have been using most tools for a while but your write up inspired me to re-build from scratch. 

Here is my question, how did you end up partitioning the hard disk? I am thinking the media would have a separate XFS partition /media and I am thinking of having a separate partition for all the docker container’s data/configuration, like the Plex metadata, etc. (e.g. /srv). How big do all your docker volumes add up to? How big would you make /srv?

**Comment by attzonko** [comment]
After some digging, I found [this](https://www.smarthomebeginner.com/ubuntu-server-partition-scheme-guide/)

It seems to be a bit old (Ubuntu 16.04) any plans to do an updated version for 20.04? Or are the recommendations still the same?

**Comment by htpcBeginner** [comment]
My partition scheme is quite simple and I am by no means an expert on filesystems etc.

Intel NUC Home Server:
POP OS 20.04 (you can use any) as I use my home server as a desktop for my use as well 
EXT4 Root partition ~50 GB
EXT4 Home partition ~300 GB - All docker app data and related stuff are in /home/user/docker folder - 

Synology DS918+ 
Synology storage is mounted on my home server using Samba/CIFS and mapped as volumes in my docker

That is basically it. I keep it simple. 

As for backup. I have a shell script that automatically backs up the whole /home/user/docker folder periodically.

**Comment by attzonko** [comment]
How full is your /home partition?


On Jul 2, 2020, at 7:30 AM, SmartHomeBeginner <notifications@github.com> wrote:

﻿
My partition scheme is quite simple and I am by no means an expert on filesystems etc.

Intel NUC Home Server:
POP OS 20.04 (you can use any) as I use my home server as a desktop for my use as well
EXT4 Root partition ~50 GB
EXT4 Home partition ~300 GB - All docker app data and related stuff are in /home/user/docker folder -

Synology DS918+
Synology storage is mounted on my home server using Samba/CIFS and mapped as volumes in my docker

That is basically it. I keep it simple.

As for backup. I have a shell script that automatically backs up the whole /home/user/docker folder periodically.

**Comment by htpcBeginner** [comment]
not much 

My docker root folder in my /home is about 45 GB and that is with nearly 15 GB of plex,emby, and jellyfin data. I also have some security camera recordings.

/var/lib/docker can grow huge over time and so having enough space in the root partition is important. 

If this answers your question, please close the issue.
