### ISSUE TITLE
Home Assistant Supervised Guide

### ISSUE THREAD

**Issue by beloso** [htpcBeginner/docker-traefik#63]
Hello @htpcBeginner,

First of all thank you for your work on this repo and posts. They've kickstarted my adventures into building my own media server.

I was using HomeAssistant (OS + Core) on a rPi for a couple of years now.
In moving it to my media server (NUC) I am struggling a bit. I got it to work but auto discovery and other components don't work now.

Could you post a guide on how do you set up your Home Assistant Supervised docker container outside of the Traefik network?

Thank you for any tips.

**Comment by htpcBeginner** [comment]
Are you using home assistant supervised on docker (NUC) or are you using core?

Either way, ensure that you are using network_mode: host

**Comment by beloso** [comment]
I am using this image `image: homeassistant/home-assistant:stable`. Which I don't think is supervised.

Which one is the supervised?

**Comment by htpcBeginner** [comment]
That is core. With that make sure you use network_mode: host

I back to using Hassio (now Home assistant supervised) on Docker: https://www.smarthomebeginner.com/install-hass-io-on-docker-linux/

**Comment by beloso** [comment]
So we need to build our own image, I think I got it. 
I'll wait up a little bit on the deprecation front. They announced they would deprecate it, now they are not. It's kinda weird where it's going.

I enabled `network_mode: host` and was able to expose it via Traefik, all good for now. I am happy with the setup, for now.

**Comment by beloso** [comment]
I'll close this up. Thank you for the response.

**Comment by proddy** [comment]
> I am using this image `image: homeassistant/home-assistant:stable`. Which I don't think is supervised.
> 
> Which one is the supervised?

I'm using the same, which is not supervised and also waiting to see what happens. It's all confusing to me too.
