### ISSUE TITLE
thank you + suggestions

### ISSUE THREAD

**Issue by thefrenchmatt** [htpcBeginner/docker-traefik#7]
I had to start with a thank you, so much effort put into this.
I compared and filtered against my own $(docker ps --format "{{ .Image }}" | sort)
Here's the things probably relevant and worth mentionning:
* `amir20/dozzle` (I checked logarr to make sure if I should keep it)
* `darathor/fail2ban:0.11` (fail2ban-docker & fail2ban-input)
* `codercom/code-server:v2` (lot of issues to get running at first)
* `jellyfin/jellyfin:latest` (successor to emby)
* `linuxserver/muximux:latest` (a nice way to put all those services in one place)
* `linuxserver/smokeping:latest` (is quite easy to reconfigure)
* `lobre/traefik-home` (this one for traefik v1, otherwise simple-traefik-dashboard for v2)
* `omertu/googlehomekodi` (works through ifttt, know one similar for plex but not using it)
* `oznu/homebridge:latest` (through a plugin, sync with gh is much simpler than ha)
* `vincentbernat/dashkiosk:latest` (although some functions should be possible with ha, this can also make other screens act as receivers)

BR. Matthieu

PS: almost forgot, `npm install -g rekcod`  and we usually need labels so :
```
cat << EOF > /tmp/di
docker inspect $1 | grep traefik
docker inspect $1 | rekcod
docker inspect $1 | grep traefik > $PWD/$1_rekcod.md ; docker inspect $1 | rekcod >> $PWD/$1_rekcod.md
echo "info also parsed to "
echo ${PWD}/$1"_rekcod.md"
EOF
chmod +x /tmp/di && sudo mv /tmp/di /usr/local/bin/
```

**Comment by htpcBeginner** [comment]
Thank you. Great suggestions. I am adding some right now. Jellyfin, I already had.
