### ISSUE TITLE
Getting 404 page not found error

### ISSUE THREAD

**Issue by NotSaifA** [htpcBeginner/docker-traefik#71]
I am getting this error for Sonarr and all the the other dockers I am trying to install. I can access them using the internal ip but I can't access them using the domain. I took the configuration from the example docker_compose.yml file

**Comment by NotSaifA** [comment]
I have found the fix, just add  - "traefik.http.routers.sonarr-rtr.tls=true" to the labels of sonarr, this enables TLS and allows the website to be accessed using the domain.

**Comment by up2entropy** [comment]
thank you.
