### ISSUE TITLE
HSTS doesn't seem to be applying

### ISSUE THREAD

**Issue by modem7** [htpcBeginner/docker-traefik#73]
I've just done a scan on https://securityheaders.com/ on a couple of my subdomains, and the results were as follows: 

![image](https://user-images.githubusercontent.com/4349962/90176346-b2a6c080-dda0-11ea-9be5-a2259ded6653.png)

I've got the settings that have been proposed in the middlewares:

![image](https://user-images.githubusercontent.com/4349962/90176432-d0742580-dda0-11ea-8a96-2b3114135fa6.png)

It seems that some of these options aren't being applied.

Not quite sure which options to investigate.

Would it also be worthwhile putting in the TLS options to better secure the site? E.g.:
```
  [tls]
    [tls.options]
      [tls.options.default]
        minVersion = "VersionTLS12"
       sniStrict = true
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
          "TLS_AES_128_GCM_SHA256",
          "TLS_AES_256_GCM_SHA384",
          "TLS_CHACHA20_POLY1305_SHA256",
          "TLS_FALLBACK_SCSV" # Client is doing version fallback. See RFC 7507.
      ]
```

**Comment by modem7** [comment]
Heya, 

Yupper! In this case I checked Plex which has no auth or oauth chains

**Comment by Motophan** [comment]
https://github.com/htpcBeginner/docker-traefik/issues/130

somewhat related, I believe the webserver will send default cert when no sni is sent.
