### ISSUE TITLE
Docker socket-proxy issue

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#80]
Before I start I notice in tour yml rules for your non-docker apps you have "HostHeader" before the subdomain you assign to it which will return unsupported function errors in traefik, you need to replace this with just "Host" and it will work.

Anyway onto my issue, basically I have implemented the same socket-proxy as you and secrets etc, but the following containers either throw errrors for not being able to authenticate with the secrets ie cf-ddns where it doesnt authenticate leading me to believe it cant use the value in the secret, or apps like portainer and dozzle cant find the docker socket anymore yet watchtower and other can with no issues. 

Please can anyone advise how to get the screts and socket proxy working for these containers below, my other 15 or so containers have no issues and function with the secrets and socket proxy.

````
  socket-proxy:
    container_name: socket-proxy
    image: fluencelabs/docker-socket-proxy
    restart: always
    networks:
      socket_proxy:
        ipv4_address: 10.0.1.2
    privileged: true
    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      - DELETE=1 # Watchtower
        # GET Optons
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer, Watchtower
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer, Watchtower
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portaienr
      - VOLUMES=1 # Portainer
      # POST Options
      - CONTAINERS_CREATE=1 # WatchTower
      - CONTAINERS_START=1 # WatchTower
      - CONTAINERS_UPDATE=1 # WatchTower
      # DELETE Options
      - CONTAINERS_DELETE=1 # WatchTower
      - IMAGES_DELETE=1 # WatchTower

  # Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    #command: -H unix:///var/run/docker.sock
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/portainer/data:/data
    environment:
      - TZ=$TZ
    ports:
      - "$PORTAINER_PORT:9000"
    networks:
      proxy_net:
        ipv4_address: 10.0.0.8
      socket_proxy:
    depends_on:
      - socket-proxy      
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    container_name: cf-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=/run/secrets/cloudflare_api_token
      - ZONE=$DOMAINNAME
      - PROXIED=true
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1
    secrets:
      - cloudflare_api_token     

  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      proxy_net:
        ipv4_address: 10.0.0.18
      socket_proxy:
    depends_on:
      - socket-proxy      
    security_opt:
      - no-new-privileges:true
    ports:
      - "$DOZZLE_PORT:8080"
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
#      DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
    #volumes:
     # - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.dozzle-rtr.entrypoints=https"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"

 
      
  # Cloudflare-Companion - Automatic CNAME DNS Creation
  cf-companion:
    container_name: cf-companion
    image: tiredofit/traefik-cloudflare-companion:latest
    restart: always
    networks:
      socket_proxy:
    depends_on:
      - socket-proxy    
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TIMEZONE=$TZ
      - TRAEFIK_VERSION=2
      - CF_EMAIL=/run/secrets/cloudflare_email
      # - CF_TOKEN=$CLOUDFLARE_API_TOKEN # Scoped api token not working. Error 10000.
      - CF_TOKEN=/run/secrets/cloudflare_api_key # Same as traefik
      - TARGET_DOMAIN=$DOMAINNAME
      - DOMAIN1=$DOMAINNAME
      - DOMAIN1_ZONE_ID=/run/secrets/cloudflare_zoneid # Copy from Cloudflare Overview page
      - DOMAIN1_PROXIED=TRUE
    secrets: # not working
      - cloudflare_email
      - cloudflare_api_key
      - cloudflare_zoneid      
    labels:
      # Add hosts specified in rules here to force cf-companion to create the CNAMEs
      # Since cf-companion creates CNAMEs based on host rules, this a workaround for non-docker/external apps
      - "traefik.http.routers.cf-companion-rtr.rule=HostHeader(`pihole1.$DOMAINNAME`) || `pihole2.$DOMAINNAME`) || `pihole3.$DOMAINNAME`) || HostHeader(`reofront.$DOMAINNAME`) || HostHeader(`reorear.$DOMAINNAME`)"

````

**Comment by tehniemer** [comment]
Just an FYI, according to Traefik docks `Host` and `HostHeader` are treated the same in v2.2

https://docs.traefik.io/routing/routers/#rule

**Comment by gzecchi** [comment]
Hi @Joeharrison94,

regarding the Socket-Proxy:

1. You have to specify in Portainer Settings a new endpoint called "socket-proxy:2375"
2. On _dozzle_ you have to add in the environment the following -> DOCKER_HOST: tcp://socket-proxy:2375
3. On _cf-companion_ you have to add in the environment the following -> DOCKER_HOST: tcp://socket-proxy:2375

regarding the Docker Secrets:
1. oznu/cloudflare-ddns cannot handle API token from file so either you can pass the token in an environment variable or change the image with one that can handle docker secrets -> in my case I've created my own cloudflare-ddns docker image that can handle Docker Secrets
2. Same as above for tiredofit/traefik-cloudflare-companion

GZ

**Comment by Joeharrison94** [comment]
> 
> 
> Just an FYI, according to Traefik docks `Host` and `HostHeader` are treated the same in v2.2
> 
> https://docs.traefik.io/routing/routers/#rule

I got errors with HostHeader and Im on the latest Chevrotin image, but Host was fine

**Comment by Joeharrison94** [comment]
> 
> 
> Hi @Joeharrison94,
> 
> regarding the Socket-Proxy:
> 
>     1. You have to specify in Portainer Settings a new endpoint called "socket-proxy:2375"
> 
>     2. On _dozzle_ you have to add in the environment the following -> DOCKER_HOST: tcp://socket-proxy:2375
> 
>     3. On _cf-companion_ you have to add in the environment the following -> DOCKER_HOST: tcp://socket-proxy:2375
> 
> 
> regarding the Docker Secrets:
> 
>     1. oznu/cloudflare-ddns cannot handle API token from file so either you can pass the token in an environment variable or change the image with one that can handle docker secrets -> in my case I've created my own cloudflare-ddns docker image that can handle Docker Secrets
> 
>     2. Same as above for tiredofit/traefik-cloudflare-companion
> 
> 
> GZ

Thank you very much for this.

Portainer and Dozzle are now all sorted thank you, would you consider sharing your image foor cloudflare-ddns. Cloudflare companion can wait Ill see if they add secret functionality.

**Comment by Joeharrison94** [comment]
Do you get warning errors still saying the secrets arent there when you start your containers but they still work ? and also in the ttraefik log I get this for every container "uses a non-existent resolver: dns-cloudflare" but it works still.

**Comment by gzecchi** [comment]
> > Hi @Joeharrison94,
> > regarding the Socket-Proxy:
> > ```
> > 1. You have to specify in Portainer Settings a new endpoint called "socket-proxy:2375"
> > 
> > 2. On _dozzle_ you have to add in the environment the following -> DOCKER_HOST: tcp://socket-proxy:2375
> > 
> > 3. On _cf-companion_ you have to add in the environment the following -> DOCKER_HOST: tcp://socket-proxy:2375
> > ```
> > 
> > 
> > regarding the Docker Secrets:
> > ```
> > 1. oznu/cloudflare-ddns cannot handle API token from file so either you can pass the token in an environment variable or change the image with one that can handle docker secrets -> in my case I've created my own cloudflare-ddns docker image that can handle Docker Secrets
> > 
> > 2. Same as above for tiredofit/traefik-cloudflare-companion
> > ```
> > 
> > 
> > GZ
> 
> Thank you very much for this.
> 
> Portainer and Dozzle are now all sorted thank you, would you consider sharing your image foor cloudflare-ddns. Cloudflare companion can wait Ill see if they add secret functionality.

My image is public and it's available from Docker Hub (https://hub.docker.com/r/gzecchi/cloudflare-ddns)

**Comment by gzecchi** [comment]
> Do you get warning errors still saying the secrets arent there when you start your containers but they still work ? and also in the ttraefik log I get this for every container "uses a non-existent resolver: dns-cloudflare" but it works still.

I haven't seen such warnings/errors, however, if you paste somewhere the message I can look into

**Comment by Joeharrison94** [comment]
> 
> 
> > Do you get warning errors still saying the secrets arent there when you start your containers but they still work ? and also in the ttraefik log I get this for every container "uses a non-existent resolver: dns-cloudflare" but it works still.
> 
> I haven't seen such warnings/errors, however, if you paste somewhere the message I can look into

Thanks I appreciate it, here are the errors that happen on compuse up and down

````
WARNING: Service "traefik" uses an undefined secret file "/mnt/docker/secrets/cloudflare_email", the following file should be created "/mnt/docker/secrets/cloudflare_email"
WARNING: Service "traefik" uses an undefined secret file "/mnt/docker/secrets/cloudflare_api_key", the following file should be created "/mnt/docker/secrets/cloudflare_api_key"
WARNING: Service "cf-ddns" uses an undefined secret file "/mnt/docker/secrets/cloudflare_api_token", the following file should be created "/mnt/docker/secrets/cloudflare_api_token"
WARNING: Service "cf-companion" uses an undefined secret file "/mnt/docker/secrets/cloudflare_email", the following file should be created "/mnt/docker/secrets/cloudflare_email"
WARNING: Service "cf-companion" uses an undefined secret file "/mnt/docker/secrets/cloudflare_api_key", the following file should be created "/mnt/docker/secrets/cloudflare_api_key"
WARNING: Service "cf-companion" uses an undefined secret file "/mnt/docker/secrets/cloudflare_zoneid", the following file should be created "/mnt/docker/secrets/cloudflare_zoneid"
WARNING: Service "authelia" uses an undefined secret file "/mnt/docker/secrets/authelia_jwt_secret", the following file should be created "/mnt/docker/secrets/authelia_jwt_secret"
WARNING: Service "authelia" uses an undefined secret file "/mnt/docker/secrets/authelia_session_secret", the following file should be created "/mnt/docker/secrets/authelia_session_secret"
WARNING: Service "authelia" uses an undefined secret file "/mnt/docker/secrets/authelia_notifier_smtp_password", the following file should be created "/mnt/docker/secrets/authelia_notifier_smtp_password"
WARNING: Service "authelia" uses an undefined secret file "/mnt/docker/secrets/authelia_duo_api_secret_key", the following file should be created "/mnt/docker/secrets/authelia_duo_api_secret_key"
WARNING: Service "guacamole" uses an undefined secret file "/mnt/docker/secrets/guac_db_name", the following file should be created "/mnt/docker/secrets/guac_db_name"
WARNING: Service "guacamole" uses an undefined secret file "/mnt/docker/secrets/guac_mysql_user", the following file should be created "/mnt/docker/secrets/guac_mysql_user"
WARNING: Service "guacamole" uses an undefined secret file "/mnt/docker/secrets/guac_mysql_password", the following file should be created "/mnt/docker/secrets/guac_mysql_password"
WARNING: Service "mariadb" uses an undefined secret file "/mnt/docker/secrets/mysql_root_password", the following file should be created "/mnt/docker/secrets/mysql_root_password"
````

**Comment by robflate** [comment]
I get the same errors only if the `secrets` folder has permissions `root:root` `600`.

**Comment by Joeharrison94** [comment]
> I get the same errors only if the `secrets` folder has permissions `root:root` `600`.

I do have them set as you said but I only do that for security purposes so is there no workaround

**Comment by robflate** [comment]
Maybe others don't see the error because they use the bash script which uses sudo for the commands? If you just do `docker-compose up -d` it runs as your user not root.

**Comment by Joeharrison94** [comment]
> Maybe others don't see the error because they use the bash script which uses sudo for the commands? If you just do `docker-compose up -d` it runs as your user not root.

That does makes sense

**Comment by Joeharrison94** [comment]
> I get the same errors only if the `secrets` folder has permissions `root:root` `600`.

I do have them set as you said but I only do that for security purposes so is there no workaround

> > Maybe others don't see the error because they use the bash script which uses sudo for the commands? If you just do `docker-compose up -d` it runs as your user not root.
> 
> That does makes sense



> Maybe others don't see the error because they use the bash script which uses sudo for the commands? If you just do `docker-compose up -d` it runs as your user not root.

But if that's the case how come the containers can still use the secrets

**Comment by ptoulouse** [comment]
Depends on the container.

I launch docker-compose as my own user (not sudo docker-compose). Therefore I need the proper permission so my user can access the file. Obviously, if you sudo, you have access to any files regardless of permissions.

Now, what that step does is just mounting the secrets files in the container at path /run/secrets. If the container runs as root, again permissions does not matter. However if you map the container to another user, than that user needs read access to the secrets files.

**Comment by htpcBeginner** [comment]
https://www.smarthomebeginner.com/traefik-docker-security-best-practices/

**Comment by undaunt** [comment]
I'm not sure this is really closed. In Your new article @htpcBeginner you cover secrets in great detail, but I don't see a mention of running compose up -d with sudo. I modified my bash aliases now to include sudo to stop getting the errors around no permission to see the secret, etc. but unless someone stumbles upon this issue page, it may affect others.
