### ISSUE TITLE
Middlewares on TCP?

### ISSUE THREAD

**Issue by undaunt** [htpcBeginner/docker-traefik#84]
Hello,

Based on your post on smarthomebeginner, and my reading of the Traefik docs, it's my understanding we cannot put middlewares on TCP routers? I was a bit confused then as I was comparing your app-pihole to app-unifi, and even though unifi is running as https entry only, and thus a TCP router (not http), it has middlewares in the rules.yml. Is this working, or just a missed removal when copying the syntax from another file?

https://github.com/htpcBeginner/docker-traefik/blob/master/traefik2/rules/app-unifi.yml.example

I tested exposing my proxmox host via TCP router and it does not appear to be triggering any middlewares.

Thanks.

**Comment by robflate** [comment]
Looks like Traefik 2.3 is more strict with this and fails to load if there’s middlewares in tcp routers. #89
