### ISSUE TITLE
Someone hacked my docker VPS. it's the stack ?

### ISSUE THREAD

**Issue by lucacalcaterra** [htpcBeginner/docker-traefik#85]
Launching the docker-compose.yml stack , after some time, someone can launch busybox and other containers with malware. I'm investigating if the flawless is on docker or on my system (i don't think, i've reinstalled it , so ...clean), but i'm guess the issue is on the exposed api port.

Someone can give me any feedbacks ? Thanks!

**Comment by lucacalcaterra** [comment]
Update: It seems blocker closing port of 2375 (socket-proxy container) on host. VERY IMPORTANT ! Do it now !!

**Comment by luwidgiani** [comment]
Can you give me some more information?

The only port on my router that's open is 80 and 443 for traefik. 
Why should i close ports for the socket proxy on the host itself? 
Did you expose it through traefik or the router?

**Comment by lucacalcaterra** [comment]
@luwidgiani Probably a bad configuration? Anyway my host have the port 2375 open from external , reachable (tested by a simple telnet, have you tried ) . I fixed disabling iptables( iptables=false in daemon.json)

**Comment by htpcBeginner** [comment]
Guys, you should never expose 2375 externally. I have UFW blocking unwanted ports. Plus, digital oceans firewall on top.

One thing though is docker does not respect iptables. There is a fix. I am not near a computer. I will share it soon.

**Comment by luwidgiani** [comment]
indeed, only port exposed shoud be 80 and 443 as stated in your docs

**Comment by lucacalcaterra** [comment]
I too was sure I had only exposed the 80 and 443 with UFW  ... But docker without iptables=false bypass it. So, double check opens ports and  follow this guide:
https://www.michelebologna.net/2018/preventing-docker-from-manipulating-iptables-rules/

**Comment by htpcBeginner** [comment]
Thats the fix. 

In addition, I will be publishing a Docker traefik stack security best practices guide either today or tomorrow that will also touch on this topic. So look out for that.
