### ISSUE TITLE
Question your about config

### ISSUE THREAD

**Issue by Joeharrison94** [htpcBeginner/docker-traefik#93]
I was wondering a few things and I'm hoping you don't mind answering them for me.

What are the reasons you would run a Firefox container?

Would you share your glances conf file?

What is redis used for in your stack ?

Is there a way to pass a gpu through to docker from the host machine to use for Plex hardware transcoding ? 

Thanks

**Comment by pemontto** [comment]
Redis is used to persist authelia sessions

For hardware transcoding, as long as you have Plex Pass, try adding this to your plexms config:
```yaml
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
```

**Comment by Joeharrison94** [comment]
Ahh that makes sense, now re redis I'll look at implementing that

**Comment by Joeharrison94** [comment]
do you still have a copy of the yaml for redis I am struggling getting secrets working for redis and rediscommmander?

**Comment by htpcBeginner** [comment]
Having firefox is like having a VPN to my network. I can browse the internet as if i am browsing from my home, from anywhere. Sometimes this is helpful to circumvent any network restrictions (eg. corporate).

**Comment by htpcBeginner** [comment]
Both redis and rediscommander ymls are in docker-compose or docker-compose-obsolete ymls in the repo. 

Please close issue if all your questions were answered.

**Comment by Joeharrison94** [comment]
> Both redis and rediscommander ymls are in docker-compose or docker-compose-obsolete ymls in the repo.
> 
> Please close issue if all your questions were answered.

Hey, I am having issues finding the redis block it isnt in any of the obsolete ymls.

**Comment by robflate** [comment]
> Hey, I am having issues finding the redis block it isnt in any of the obsolete ymls.

https://github.com/htpcBeginner/docker-traefik/blob/2cdb3991fa24c189cf38c1d8cc30b903b56bf9c3/docker-compose-t2-web.yml#L288

You can search inside a repository by using the search box and clicking `In this repository`. Like this;

https://github.com/htpcBeginner/docker-traefik/search?q=redis
